/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .gitlab-ci.yaml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'local'

// Config for firebase
export const firebase = {
  apiKey: "AIzaSyCCU2VeOmng3BbpGcDzX79D9lTMmsRs9Gw",
  authDomain: "lucky-aed54.firebaseapp.com",
  databaseURL: "https://lucky-aed54.firebaseio.com",
  projectId: "lucky-aed54",
  storageBucket: "lucky-aed54.appspot.com",
  messagingSenderId: "836535631836"
}

// Config to override default reduxFirebase config in store/createStore
// which is not environment specific.
// For more details, visit http://react-redux-firebase.com/docs/api/enhancer.html
export const reduxFirebase = {
  enableLogging: false, // enable/disable Firebase Database Logging
}

export default {
  env,
  firebase,
  reduxFirebase
}
